//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.18 at 02:07:40 PM EDT 
//


package org.airavata.client.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.airavata.client.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OutputLocation_QNAME = new QName("", "outputLocation");
    private final static QName _Queuename_QNAME = new QName("", "queuename");
    private final static QName _Processorcount_QNAME = new QName("", "processorcount");
    private final static QName _Emailid_QNAME = new QName("", "emailid");
    private final static QName _Outputlocation_QNAME = new QName("", "outputlocation");
    private final static QName _Stderrlocation_QNAME = new QName("", "stderrlocation");
    private final static QName _Method_QNAME = new QName("", "Method");
    private final static QName _Walltime_QNAME = new QName("", "walltime");
    private final static QName _Message_QNAME = new QName("", "message");
    private final static QName _Executable_QNAME = new QName("", "executable");
    private final static QName _Emailparam_QNAME = new QName("", "emailparam");
    private final static QName _Stdoutlocation_QNAME = new QName("", "stdoutlocation");
    private final static QName _Hostname_QNAME = new QName("", "hostname");
    private final static QName _Hostcount_QNAME = new QName("", "hostcount");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Experimentid_QNAME = new QName("", "experimentid");
    private final static QName _ApplicationId_QNAME = new QName("", "applicationId");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _ExperimentName_QNAME = new QName("", "experimentName");
    private final static QName _Userdn_QNAME = new QName("", "userdn");
    private final static QName _Status_QNAME = new QName("", "status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.airavata.client.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outputLocation")
    public JAXBElement<String> createOutputLocation(String value) {
        return new JAXBElement<String>(_OutputLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "queuename")
    public JAXBElement<String> createQueuename(String value) {
        return new JAXBElement<String>(_Queuename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "processorcount")
    public JAXBElement<Integer> createProcessorcount(Integer value) {
        return new JAXBElement<Integer>(_Processorcount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "emailid")
    public JAXBElement<String> createEmailid(String value) {
        return new JAXBElement<String>(_Emailid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outputlocation")
    public JAXBElement<String> createOutputlocation(String value) {
        return new JAXBElement<String>(_Outputlocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stderrlocation")
    public JAXBElement<String> createStderrlocation(String value) {
        return new JAXBElement<String>(_Stderrlocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Method")
    public JAXBElement<String> createMethod(String value) {
        return new JAXBElement<String>(_Method_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "walltime")
    public JAXBElement<Integer> createWalltime(Integer value) {
        return new JAXBElement<Integer>(_Walltime_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "executable")
    public JAXBElement<String> createExecutable(String value) {
        return new JAXBElement<String>(_Executable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "emailparam")
    public JAXBElement<String> createEmailparam(String value) {
        return new JAXBElement<String>(_Emailparam_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stdoutlocation")
    public JAXBElement<String> createStdoutlocation(String value) {
        return new JAXBElement<String>(_Stdoutlocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostname")
    public JAXBElement<String> createHostname(String value) {
        return new JAXBElement<String>(_Hostname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostcount")
    public JAXBElement<Integer> createHostcount(Integer value) {
        return new JAXBElement<Integer>(_Hostcount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "experimentid")
    public JAXBElement<String> createExperimentid(String value) {
        return new JAXBElement<String>(_Experimentid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "applicationId")
    public JAXBElement<String> createApplicationId(String value) {
        return new JAXBElement<String>(_ApplicationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "experimentName")
    public JAXBElement<String> createExperimentName(String value) {
        return new JAXBElement<String>(_ExperimentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userdn")
    public JAXBElement<String> createUserdn(String value) {
        return new JAXBElement<String>(_Userdn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

}
